name: Deploy MkDocs to FTP

on:
  push:
    branches:
      - main
concurrency:
  group: deploy-ftp
  cancel-in-progress: true

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Build MkDocs
        run: mkdocs build

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/ai-project-playbook/  # Upload naar deze map
          local-dir: ./site/            # Dit is de map waar MkDocs de site bouwt
          protocol: ftp                # Gebruik 'ftp' of 'ftps'

